### ISSUE TITLE
questions about Openbanking

### ISSUE THREAD

**Issue by shalva97** [TBCBank/TBC.OpenBanking.Jws#2]
გამარჯობა, გადავწყვიტე გამერჩია ეს Openbanking როგორ მუშაობს. მე როგორც მივხვდი ჯერ მჭირდება consent, თუ ამას მომცემს სერვერი შემეძლება მომხმარებლის ბანკის ინფორმაცია წამოვიღო სერვერიდან. მაგრამ როგორ დავიწყო ვერ მივხვდი. ან როგორ მივუთითო რომელი მომხმარებლის ანგარიში მაინტერესბს

მხოლოდ კოტლინი ვიცი. მინდა რომ პატარა კონსოლ აპი დავწერო, რომელიც წამოიღებს ჩემს გადარიცხვებს და ანგარიშებს.

დავრეგისტრირდი https://developers.tbcbank.ge -ზე და დავამატე MyApp-ში ჩემი აპი, რო გადავდივარ მიწერს რომ Open Banking Services -> Enabled არისო. მსგრამ მჭირდება მე ეს App ID ან რისთვის გამოიყენება ეს?

https://developers.tbcbank.ge/reference/createconsent აქ არი ნაჩვენები რექუესთი მაგრამ რო ვაგზავნი POST request-ს 500 მომდის
Request
```
POST https://test-openbanking.tbcbank.ge/0.6/v1/consents

{
     "access": {
          "allPsd2": "allAccounts"
     },
     "recurringIndicator": true,
     "validUntil": "2020-12-31",
     "frequencyPerDay": 4,
     "combinedServiceIndicator": true
}
```

Response:
```
{
    "type": "https://developers.tbcbank.ge/docs/error-type-500",
    "title": "Unknown server error",
    "status": 500,
    "detail": "Something went wrong in the proxy",
    "systemCode": "System code for problem is psd2_consents.ExecutionReturnedFailure.500.001",
    "code": ""
}
```

შენ რაც დაწერერიდმიში ეგეთი რაღაცა მინდა მეც პლუს ტრანზაქციების წამოღება, მარა ლოკლურად გაქვს გაშვებული... მოკლედ, რეალურ თიბისის სერვერის ლინკი რომელია? openbanking.tbcbank.ge/0.6/v1/consents ვცადე და `SSLV3_ALERT_HANDSHAKE_FAILURE` მომდის.

ამ სერთიფიკატებსაც ვერ მივუხვდი, რატო ამატებ შენსას? დავუშვათ როგორღაც დავამატე თიბისი ჩემს აპში, მერე საქართველო რო დავამატო იმათ ცალკე სხვა სერთიფიკატი აქვთ?

**Comment by galkhazishvili** [comment]
გამარჯობა გიორგი. ეს რეპოზიტორი შეიცავს ღია ბანკინგისთვის საჭირო ციფრული ხელმოწერის კომპონენტს. აქ ნამდვილად ვერ დავიწყებთ developers.tbcbank.ge-თან დაკავშირებულ საუბარს. ამას სხვა გუნდი მართავს. შენ შეტყობინებას გადავცემთ.
